### ISSUE TITLE
Keep references on modules

### ISSUE THREAD

**Issue by ZorGleH** [jacomyal/domino.js#23]
It would be great to have a reference on modules in the domino instance. This way you don't need to store them outside domino. Maybe you can give an ID to each module so you can find it like so:

``` javascript
domino.instances('foo').modules('bar')
```

**Comment by jacomyal** [comment]
OK, that would be indeed pretty useful. I will implement it as for domino instances:
- If you do not give an ID to your module, then it will not be reachable through the instance like this.
- If you use an ID, first you will be able to reach it through the `.modules()` method. Also, you will not be able to create another module in the same domino instance with the same ID, until you killed the old one.

**Comment by ZorGleH** [comment]
Sounds good.
