### ISSUE TITLE
Initial value missing = null for unrequired property?

### ISSUE THREAD

**Issue by ZorGleH** [jacomyal/domino.js#24]
Why not assume initial value missing is null when `type: '?x'`?
It could avoid writing explicitly `value: null`.

**Comment by jacomyal** [comment]
I'm not sure.
It happened to me to forget declaring the initial value or to declare it under the wrong key. And in this case, I am pretty happy to see the error triggered.
Finally, this is an error only in `strict` mode - and that makes sense, I think.
