### ISSUE TITLE
List available structures

### ISSUE THREAD

**Issue by ZorGleH** [jacomyal/domino.js#49]
Is it possible to list available (globally and locally) structures?

**Comment by jacomyal** [comment]
Not yet. I just have to add a `domino.struct.get(?key)` that returns the related structure or every structures. It will be added in the next release.

Also, there are also no local structures yet - and I do not plan to add this feature by now.

**Comment by ZorGleH** [comment]
Ok, nice!

2013/9/19 Alexis Jacomy notifications@github.com

> Not yet. I just have to add a domino.struct.get(?key) that returns the
> related structure or every structures. It will be added in the next release.
> 
> Also, there are also no local structures yet - and I do not plan to add
> this feature by now.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jacomyal/domino.js/issues/49#issuecomment-24737148
> .

## 

Grégoire Dubourg
1084 rue de Paris
60520 La Chapelle-en-Serval
06 82 36 45 23
09 53 89 43 54
