### ISSUE TITLE
URL corrupted by domino (ajax)

### ISSUE THREAD

**Issue by jacomyma** [jacomyal/domino.js#5]
When trying to make an ajax call to a URL with a port, the column is stripped and it fails.
Example: trying to send a post to:
http://fake.fr:6966/
Result: the post fails with this message:
POST http://fake.fr6966/  

The issue comes from the loop at this point of the code:
https://github.com/jacomyal/domino.js/blob/master/src/domino.js#L579
(I tested that before, the URL is OK and after, it is corrupted).

**Comment by jacomyal** [comment]
Oops, indeed:
The default shortcut prefix is ":", and it seems to be removed when the shortcut does not match anything.

I'll take care of that ASAP, thanks a lot!
